### ISSUE TITLE
Cannot refill regions

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#124]
Can you fix this asap and report directly to me? So I refill the db. Stack trace below

API & docs are now on api.got.show

``` bash
npm run refill --collection=regions

> got-api@0.0.1 refill /home/cdallago/api
> node scripts/refill.js

Refilling collection: regions
Going to connect to mongodb://34g98vyb4cuic3:9743yrubvh8rheuihb38@ds054128.mlab.com:54128/js16
Mongoose connected
Filling started.
Scrapping from wiki. May take a while..
start getRegions
Fetching North of the Wall
Fetching The North
Fetching The Riverlands
Fetching The Vale
Fetching The Iron Islands
Fetching The Westerlands
Fetching The Reach
Fetching The Crownlands
Fetching The Stormlands
Fetching Dorne
Fetching Free Cities
Fetching Slaver's Bay
Fetching Dothraki Sea
Fetching Red Waste
Fetching Valyrian peninsula
Fetching Other
Fetching Naath
Fetching Isle of Tears
Fetching Basilisk Point
/home/cdallago/api/app/controllers/scraper/regions.js:36
                    if(data.parse.redirects.length > 0) {
                           ^

TypeError: Cannot read property 'parse' of undefined
    at /home/cdallago/api/app/controllers/scraper/regions.js:36:13
    at Request._callback (/home/cdallago/api/node_modules/nodemw/lib/api.js:219:5)
    at Request.self.callback (/home/cdallago/api/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/cdallago/api/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/home/cdallago/api/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)

npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/home/cdallago/node/bin/node" "/usr/local/bin/npm" "run" "refill" "--collection=regions"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! got-api@0.0.1 refill: `node scripts/refill.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the got-api@0.0.1 refill script 'node scripts/refill.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the got-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/refill.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs got-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls got-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cdallago/api/npm-debug.log
```

**Comment by sacdallago** [comment]
Also. What is the `characterlocations` collection for? It is empty after filling everything /regions!

**Comment by kordianbruck** [comment]
@sacdallago `characterlocations` is its own collection/filler

**Comment by sacdallago** [comment]
@kordianbruck I called you. You didn't want me </3

**Comment by ghost** [comment]
@theocheslerean

**Comment by ghost** [comment]
@sacdallago I fixed it.

**Comment by ghost** [comment]
@sacdallago charactersLocations is not empty for me after refilling. There are more than 2000 wiki pages to scrap, so this might take a while.

**Comment by sacdallago** [comment]
I did that. Just that it was not in the Readme + the upper an lower case!
So I pull and fill the regions now

**Comment by sacdallago** [comment]
P.S.: all the sudden I feel so @kordianbruck

**Comment by kordianbruck** [comment]
@sacdallago did you consider changing your name? Like after we marry?

**Comment by sacdallago** [comment]
You mean after we marry :ring:
