### ISSUE TITLE
Sentiment/edit function

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectA#128]
Hey I think we found an error with the sentiment/edit -function
Project D 5 stored some data as a negativ value though it should be stored positive.
Now we wrote the following script to resolve that problem using the edit-url of the database.

``` javascript
var request = require('request');

var allURL = "https://api.got.show/api/sentiment";
var changeURL ="https://api.got.show/api/sentiment/edit/:id?token=xxx";

request.get(allURL, function(err, resp, body){
   var json = JSON.parse(body);
   json.forEach(function(currentValue, index, array){
       if(currentValue.negSum < 0){
           currentValue.negSum = currentValue.negSum * (-1);
       }
       if(currentValue.negCount < 0){
           currentValue.negCount = currentValue.negCount * (-1);
       }
       changeURL = changeURL.replace('id',currentValue._id);
       request({
           method: "PUT",
           uri: changeURL,
           form: {
               'negSum' : currentValue.negSum,
               'negCount' : currentValue.negCount
           }
       }, function(err, resp, body){
           console.error(err);
           console.log(body);
       });
   });
});
```

Nothing happens and works. Is it possible that there is an intern error in the code of Project A. 
The log is postet [here](https://github.com/Rostlab/JS16_ProjectD_Group5/issues/94#issuecomment-204467851).

```
[Fri Apr 01 2016 12:57:48]C:\Users\jonas\Documents\GitHub\JS16_ProjectA\app\stores\charactersSentiment.js:127
                callback(2, id);
                ^

TypeError: callback is not a function
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\app\stores\charactersSentiment.js:127:17
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\app\stores\charactersSentiment.js:94:17
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\app\stores\charactersSentiment.js:41:17
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\node_modules\mongoose\node_modules\kareem\index.js:160:11
    at Query._find (C:\Users\jonas\Documents\GitHub\JS16_ProjectA\node_modules\mongoose\lib\query.js:1018:5)
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\node_modules\mongoose\node_modules\kareem\index.js:156:8
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\node_modules\mongoose\node_modules\kareem\index.js:18:7
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

Is it possible that there is a  bug inside of the function? Can you take a look?

**Comment by togiberlin** [comment]
@kordianbruck please pull newest codebase to your server :) @jonny3576 I hope it should be fine now...

**Comment by kordianbruck** [comment]
@sacdallago please pull and update :dancer: :dancers:

**Comment by jcebel** [comment]
Thanks for the quick reaction! I solved it with a work around for me, because I wasn't thinking of posting it here, my fault. 
But I think this should be solved now.

**Comment by sacdallago** [comment]
I just open it and assign it to myself so I remember tomorrow mornin'

**Comment by sacdallago** [comment]
Done
