### ISSUE TITLE
api.got.show/api/characters/byslug crashes API

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectA#139]
https://api.got.show/doc/#api-Characters-GetBySlug

```
ReferenceError: slug is not defined
   at Object.module.exports.getBySlug (/home/cdallago/api/app/stores/characters.js:71:98)
   at module.exports.getBySlug (/home/cdallago/api/app/controllers/character.js:128:25)
   at Layer.handle [as handle_request] (/home/cdallago/api/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/cdallago/api/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/cdallago/api/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/cdallago/api/node_modules/express/lib/router/layer.js:95:5)
   at /home/cdallago/api/node_modules/express/lib/router/index.js:277:22
   at param (/home/cdallago/api/node_modules/express/lib/router/index.js:349:14)
   at param (/home/cdallago/api/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/home/cdallago/api/node_modules/express/lib/router/index.js:410:3)
   at next (/home/cdallago/api/node_modules/express/lib/router/index.js:271:10)
   at /home/cdallago/api/startUp.js:121:32
   at Layer.handle [as handle_request] (/home/cdallago/api/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/cdallago/api/node_modules/express/lib/router/index.js:312:13)
   at /home/cdallago/api/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/cdallago/api/node_modules/express/lib/router/index.js:330:12)
```

**Comment by ghost** [comment]
Fixed.

**Comment by sacdallago** [comment]
Thanks @Adiolis 
Please @boriside be careful when implementing feature and **test, test, test**
