### ISSUE TITLE
failed get all ages operaton

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectA#39]
GET
https://got-api.bruck.me/api/ages/

TypeError: Cannot read property 'ObjectId' of undefined
   at Object.<anonymous> (/home/kb/JS16_ProjectA/app/models/age.js:8:37)
   at Module._compile (module.js:413:34)
   at Object.Module._extensions..js (module.js:422:10)
   at Module.load (module.js:357:32)
   at Function.Module._load (module.js:314:12)
   at Module.require (module.js:367:17)
   at require (internal/module.js:16:19)
   at Object.<anonymous> (/home/kb/JS16_ProjectA/app/stores/ages.js:1:73)
   at Module._compile (module.js:413:34)
   at Object.Module._extensions..js (module.js:422:10)
   at Module.load (module.js:357:32)
   at Function.Module._load (module.js:314:12)
   at Module.require (module.js:367:17)
   at require (internal/module.js:16:19)
   at module.exports.getAll (/home/kb/JS16_ProjectA/app/controllers/age.js:63:25)
   at Layer.handle [as handle_request](/home/kb/JS16_ProjectA/node_modules/express/lib/router/layer.js:95:5)

**Comment by ghost** [comment]
Two typos. I fixed it.

**Comment by kordianbruck** [comment]
@Adiolis before closing the issue, assign the issue to me, so I know to update the server. Thanks!

**Comment by sacdallago** [comment]
Off topic: @Adiolis you updated the picture!!!!!! AHAHAHAH thanks! I was just joking, but I appreciate nevertheless
